### ISSUE TITLE
404 instead of 500s for bad calls in eRegs

### ISSUE THREAD

**Issue by LindsayYoung** [fecgov/fec-eregs#385]
This came up in scanning. I think there should be a way add some resolve or 404 logic with django

**Comment by AmyKort** [comment]
@ccostino

**Comment by ccostino** [comment]
I caught up with @LindsayYoung and what we're after here is updating the URL resolution (routing) to go through the e-regs application itself instead of the proxy app/router right now.  What this means is making sure the e-regs application has the routes setup to handle these URLs if it doesn't already, and possibly updating some view logic to make use of Django's [`get_object_or_404()`](https://docs.djangoproject.com/en/2.0/topics/http/shortcuts/#get-object-or-404) method.

**Comment by ccostino** [comment]
These 500 errors may also be related to https://github.com/eregs/regulations-site/issues/485 - I'm seeing a lot of these in the logs recently.

**Comment by ccostino** [comment]
This issue will need to be fixed in https://github.com/eregs/regulations-site, not here.

**Comment by ccostino** [comment]
Seeing as how this is something that has to be done in the core eregs platform, all we should have to do once this is addressed is update the dependency for `regulations-site` to the new version once it's available.

**Comment by lbeaufort** [comment]
Update: The PR to eregs (https://github.com/eregs/regulations-site/pull/515) was merged. Once there's a new release, we need to update our `requirements.txt` (https://github.com/fecgov/fec-eregs/blob/develop/requirements.txt#L22) with the new `regulation-site` version here: https://github.com/eregs/regulations-site/blob/master/setup.py#L6

**Comment by lbeaufort** [comment]
Addressed by https://github.com/fecgov/fec-eregs/pull/405
