### ISSUE TITLE
[SNYK: HIGH] HTTP Header Injection (Django) (Due: 06/11/2021)

### ISSUE THREAD

**Issue by fec-jli** [fecgov/fec-eregs#600]
**Overview**
django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.

Affected versions of this package are vulnerable to HTTP Header Injection. In Python 3.9.5+ urllib.parse() automatically removes ASCII newlines and tabs from URLs. Unfortunately it created an issue in the URLValidator. URLValidator uses urllib.urlsplit() and urllib.urlunsplit() for creating a URL variant with Punycode which no longer contains newlines and tabs in Python 3.9.5+. As a consequence, the regular expression matched the URL (without unsafe characters) and the source value (with unsafe characters) was considered valid.

**Introduced through**
 bpo-43882 fix

**Remediation:**
Upgrade django to version 3.2.2, 3.1.10, 2.2.22 or higher.
https://app.snyk.io/vuln/SNYK-PYTHON-DJANGO-1290072

**Completion criteria:**

 - [ ] update django  to version 3.2.2, 3.1.10, 2.2.22 or higher.

**Comment by lbeaufort** [comment]
This vulnerability seems to only apply to using `URLValidator` with Python 3.9.5+. A complicating factor to updating anyway is that our eregs upstream dependencies require lower Django versions. 

```
regcore 4.2.0 has requirement django<1.12,>=1.8
django-overextends 0.4.3 has requirement django<2.0,>=1.8
regulations 8.4.2 has requirement django<1.12,>=1.8
```

Because we're not using `URLValidator` or Python 3.9.5+, I'm marking this as a false positive. 

From https://www.djangoproject.com/weblog/2021/may/06/security-releases/:
On Python 3.9.5+, URLValidator didn't prohibit newlines and tabs. If you used values with newlines in HTTP response, you could suffer from header injection attacks. Django itself wasn't vulnerable because HttpResponse prohibits newlines in HTTP headers.

Moreover, the URLField form field which uses URLValidator silently removes newlines and tabs on Python 3.9.5+, so the possibility of newlines entering your data only existed if you are using this validator outside of the form fields.
